### ISSUE TITLE
Add "Find unused exports" extension to the package

### ISSUE THREAD

**Issue by iulianraduat** [Gydunhn/Typescript-Essentials#1]
Hi Javier,

I would like to suggest you the addition of https://marketplace.visualstudio.com/items?itemName=iulian-radu-at.find-unused-exports

I am a senior typescript developer and based on my needs I developed this extension (until eslint will provide support for detection of unused exports). This extension can also detect circular imports which can produce bugs hard to explain (like importing a variable/function which is defined but it is imported as undefined).

Cheers,
Iulian

**Comment by Gydunhn** [comment]
Hi Iulian,

Thanks, I have to test it first and if it fits the needs of the team's projects I will incorporate it, but for now I have not had time for anything, I am quite busy, as soon as I have a chance to test it, I will.

**Comment by iulianraduat** [comment]
Hi @Gydunhn,

Thanks. It is perfect.

Cheers,
Iulian

**Comment by Gydunhn** [comment]
Well, even though it took me a lot of time (an excessive amount of time), this request is approved, with version 1.0.2, now the issue is closed
